/* Object identifiers (OIDs) used by FreeS/WAN
 * Copyright (C) 2003-2004 Andreas Steffen, Zuercher Hochschule Winterthur
 * 
 * This file has been automatically generated by the script oid.pl
 * Do not edit manually!
 */

typedef struct {
    u_char octet;
    u_int  next;
    u_int  down;
    const u_char *name;
} oid_t;

extern const oid_t oid_names[];

#define OID_UNKNOWN			-1
#define OID_ROLE			35
#define OID_SUBJECT_KEY_ID		38
#define OID_SUBJECT_ALT_NAME		41
#define OID_BASIC_CONSTRAINTS		43
#define OID_CRL_NUMBER			44
#define OID_CRL_REASON_CODE		45
#define OID_CRL_DISTRIBUTION_POINTS	46
#define OID_AUTHORITY_KEY_ID		48
#define OID_EXTENDED_KEY_USAGE		49
#define OID_TARGET_INFORMATION		50
#define OID_NO_REV_AVAIL		51
#define OID_RSA_ENCRYPTION		60
#define OID_MD2_WITH_RSA		61
#define OID_MD5_WITH_RSA		62
#define OID_SHA1_WITH_RSA		63
#define OID_SHA256_WITH_RSA		64
#define OID_SHA384_WITH_RSA		65
#define OID_SHA512_WITH_RSA		66
#define OID_PKCS7_DATA			68
#define OID_PKCS7_SIGNED_DATA		69
#define OID_PKCS7_ENVELOPED_DATA	70
#define OID_PKCS7_SIGNED_ENVELOPED_DATA	71
#define OID_PKCS7_DIGESTED_DATA		72
#define OID_PKCS7_ENCRYPTED_DATA	73
#define OID_PKCS9_EMAIL			75
#define OID_PKCS9_CONTENT_TYPE		77
#define OID_PKCS9_MESSAGE_DIGEST	78
#define OID_PKCS9_SIGNING_TIME		79
#define OID_MD2				85
#define OID_MD5				86
#define OID_3DES_EDE_CBC		88
#define OID_AUTHORITY_INFO_ACCESS	110
#define OID_OCSP_SIGNING		120
#define OID_XMPP_ADDR			122
#define OID_AUTHENTICATION_INFO		124
#define OID_ACCESS_IDENTITY		125
#define OID_CHARGING_IDENTITY		126
#define OID_GROUP			127
#define OID_OCSP			129
#define OID_BASIC			130
#define OID_NONCE			131
#define OID_CRL				132
#define OID_RESPONSE			133
#define OID_NO_CHECK			134
#define OID_ARCHIVE_CUTOFF		135
#define OID_SERVICE_LOCATOR		136
#define OID_DES_CBC			140
#define OID_SHA1			141
#define OID_SHA1_WITH_RSA_OIW		142
#define OID_SHA256			158
#define OID_SHA384			159
#define OID_SHA512			160
#define OID_NS_REVOCATION_URL		166
#define OID_NS_CA_REVOCATION_URL	167
#define OID_NS_CA_POLICY_URL		168
#define OID_NS_COMMENT			169
#define OID_PKI_MESSAGE_TYPE		178
#define OID_PKI_STATUS			179
#define OID_PKI_FAIL_INFO		180
#define OID_PKI_SENDER_NONCE		181
#define OID_PKI_RECIPIENT_NONCE		182
#define OID_PKI_TRANS_ID		183
