usr/lib/ipsec/charon       usr/lib/ipsec/
usr/lib/ipsec/plugins/libstrongswan-kernel-netlink.so*     usr/lib/ipsec/plugins/
usr/lib/ipsec/plugins/libstrongswan-eap*.so*     usr/lib/ipsec/plugins/
usr/lib/ipsec/plugins/libstrongswan-agent.so*      usr/lib/ipsec/plugins/
usr/lib/ipsec/plugins/libstrongswan-curl.so*       usr/lib/ipsec/plugins/
usr/lib/ipsec/plugins/libstrongswan-ldap.so*       usr/lib/ipsec/plugins/
