/* Object identifiers (OIDs) used by FreeS/WAN
 * Copyright (C) 2003-2008 Andreas Steffen, Hochschule fuer Technik Rapperswil
 * 
 * This file has been automatically generated by the script oid.pl
 * Do not edit manually!
 */

#ifndef OID_H_
#define OID_H_

typedef struct {
    u_char octet;
    u_int  next;
    u_int  down;
    const u_char *name;
} oid_t;

extern const oid_t oid_names[];

#define OID_UNKNOWN							-1
#define OID_ROLE							35
#define OID_SUBJECT_KEY_ID					38
#define OID_SUBJECT_ALT_NAME				41
#define OID_BASIC_CONSTRAINTS				43
#define OID_CRL_NUMBER						44
#define OID_CRL_REASON_CODE					45
#define OID_CRL_DISTRIBUTION_POINTS			46
#define OID_AUTHORITY_KEY_ID				48
#define OID_EXTENDED_KEY_USAGE				49
#define OID_TARGET_INFORMATION				50
#define OID_NO_REV_AVAIL					51
#define OID_RSA_ENCRYPTION					65
#define OID_MD2_WITH_RSA					66
#define OID_MD5_WITH_RSA					67
#define OID_SHA1_WITH_RSA					68
#define OID_SHA256_WITH_RSA					69
#define OID_SHA384_WITH_RSA					70
#define OID_SHA512_WITH_RSA					71
#define OID_PKCS7_DATA						73
#define OID_PKCS7_SIGNED_DATA				74
#define OID_PKCS7_ENVELOPED_DATA			75
#define OID_PKCS7_SIGNED_ENVELOPED_DATA		76
#define OID_PKCS7_DIGESTED_DATA				77
#define OID_PKCS7_ENCRYPTED_DATA			78
#define OID_PKCS9_EMAIL						80
#define OID_PKCS9_CONTENT_TYPE				82
#define OID_PKCS9_MESSAGE_DIGEST			83
#define OID_PKCS9_SIGNING_TIME				84
#define OID_MD2								91
#define OID_MD5								92
#define OID_3DES_EDE_CBC					94
#define OID_AUTHORITY_INFO_ACCESS			120
#define OID_OCSP_SIGNING					130
#define OID_XMPP_ADDR						132
#define OID_AUTHENTICATION_INFO				134
#define OID_ACCESS_IDENTITY					135
#define OID_CHARGING_IDENTITY				136
#define OID_GROUP							137
#define OID_OCSP							139
#define OID_BASIC							140
#define OID_NONCE							141
#define OID_CRL								142
#define OID_RESPONSE						143
#define OID_NO_CHECK						144
#define OID_ARCHIVE_CUTOFF					145
#define OID_SERVICE_LOCATOR					146
#define OID_CA_ISSUERS						147
#define OID_DES_CBC							151
#define OID_SHA1							152
#define OID_SHA1_WITH_RSA_OIW				153
#define OID_SHA256							169
#define OID_SHA384							170
#define OID_SHA512							171
#define OID_NS_REVOCATION_URL				177
#define OID_NS_CA_REVOCATION_URL			178
#define OID_NS_CA_POLICY_URL				179
#define OID_NS_COMMENT						180
#define OID_PKI_MESSAGE_TYPE				189
#define OID_PKI_STATUS						190
#define OID_PKI_FAIL_INFO					191
#define OID_PKI_SENDER_NONCE				192
#define OID_PKI_RECIPIENT_NONCE				193
#define OID_PKI_TRANS_ID					194

#endif /* OID_H_ */
