/* List of some useful object identifiers (OIDs)
 * Copyright (C) 2003-2004 Andreas Steffen, Zuercher Hochschule Winterthur
 * 
 * This file has been automatically generated by the script oid.pl
 * Do not edit manually!
 */

#include <stdlib.h>

#include "oid.h"

const oid_t oid_names[] = {
  {0x02,                       7, 1, "ITU-T Administration"   },  /*   0 */
  {  0x82,                     0, 1, ""                       },  /*   1 */
  {    0x06,                   0, 1, "Germany ITU-T member"   },  /*   2 */
  {      0x01,                 0, 1, "Deutsche Telekom AG"    },  /*   3 */
  {        0x0A,               0, 1, ""                       },  /*   4 */
  {          0x07,             0, 1, ""                       },  /*   5 */
  {            0x14,           0, 0, "ND"                     },  /*   6 */
  {0x09,                      18, 1, "data"                   },  /*   7 */
  {  0x92,                     0, 1, ""                       },  /*   8 */
  {    0x26,                   0, 1, ""                       },  /*   9 */
  {      0x89,                 0, 1, ""                       },  /*  10 */
  {        0x93,               0, 1, ""                       },  /*  11 */
  {          0xF2,             0, 1, ""                       },  /*  12 */
  {            0x2C,           0, 1, ""                       },  /*  13 */
  {              0x64,         0, 1, "pilot"                  },  /*  14 */
  {                0x01,       0, 1, "pilotAttributeType"     },  /*  15 */
  {                  0x01,    17, 0, "UID"                    },  /*  16 */
  {                  0x19,     0, 0, "DC"                     },  /*  17 */
  {0x55,                      52, 1, "X.500"                  },  /*  18 */
  {  0x04,                    36, 1, "X.509"                  },  /*  19 */
  {    0x03,                  21, 0, "CN"                     },  /*  20 */
  {    0x04,                  22, 0, "S"                      },  /*  21 */
  {    0x05,                  23, 0, "SN"                     },  /*  22 */
  {    0x06,                  24, 0, "C"                      },  /*  23 */
  {    0x07,                  25, 0, "L"                      },  /*  24 */
  {    0x08,                  26, 0, "ST"                     },  /*  25 */
  {    0x0A,                  27, 0, "O"                      },  /*  26 */
  {    0x0B,                  28, 0, "OU"                     },  /*  27 */
  {    0x0C,                  29, 0, "T"                      },  /*  28 */
  {    0x0D,                  30, 0, "D"                      },  /*  29 */
  {    0x24,                  31, 0, "userCertificate"        },  /*  30 */
  {    0x29,                  32, 0, "N"                      },  /*  31 */
  {    0x2A,                  33, 0, "G"                      },  /*  32 */
  {    0x2B,                  34, 0, "I"                      },  /*  33 */
  {    0x2D,                  35, 0, "ID"                     },  /*  34 */
  {    0x48,                   0, 0, "role"                   },  /*  35 */
  {  0x1D,                     0, 1, "id-ce"                  },  /*  36 */
  {    0x09,                  38, 0, "subjectDirectoryAttrs"  },  /*  37 */
  {    0x0E,                  39, 0, "subjectKeyIdentifier"   },  /*  38 */
  {    0x0F,                  40, 0, "keyUsage"               },  /*  39 */
  {    0x10,                  41, 0, "privateKeyUsagePeriod"  },  /*  40 */
  {    0x11,                  42, 0, "subjectAltName"         },  /*  41 */
  {    0x12,                  43, 0, "issuerAltName"          },  /*  42 */
  {    0x13,                  44, 0, "basicConstraints"       },  /*  43 */
  {    0x14,                  45, 0, "crlNumber"              },  /*  44 */
  {    0x15,                  46, 0, "reasonCode"             },  /*  45 */
  {    0x1F,                  47, 0, "crlDistributionPoints"  },  /*  46 */
  {    0x20,                  48, 0, "certificatePolicies"    },  /*  47 */
  {    0x23,                  49, 0, "authorityKeyIdentifier" },  /*  48 */
  {    0x25,                  50, 0, "extendedKeyUsage"       },  /*  49 */
  {    0x37,                  51, 0, "targetInformation"      },  /*  50 */
  {    0x38,                   0, 0, "noRevAvail"             },  /*  51 */
  {0x2A,                      94, 1, ""                       },  /*  52 */
  {  0x86,                     0, 1, ""                       },  /*  53 */
  {    0x48,                   0, 1, ""                       },  /*  54 */
  {      0x86,                 0, 1, ""                       },  /*  55 */
  {        0xF6,              61, 1, ""                       },  /*  56 */
  {          0x7D,             0, 1, "NortelNetworks"         },  /*  57 */
  {            0x07,           0, 1, "Entrust"                },  /*  58 */
  {              0x41,         0, 1, "nsn-ce"                 },  /*  59 */
  {                0x00,       0, 0, "entrustVersInfo"        },  /*  60 */
  {        0xF7,               0, 1, ""                       },  /*  61 */
  {          0x0D,             0, 1, "RSADSI"                 },  /*  62 */
  {            0x01,          89, 1, "PKCS"                   },  /*  63 */
  {              0x01,        72, 1, "PKCS-1"                 },  /*  64 */
  {                0x01,      66, 0, "rsaEncryption"          },  /*  65 */
  {                0x02,      67, 0, "md2WithRSAEncryption"   },  /*  66 */
  {                0x04,      68, 0, "md5WithRSAEncryption"   },  /*  67 */
  {                0x05,      69, 0, "sha-1WithRSAEncryption" },  /*  68 */
  {                0x0B,      70, 0, "sha256WithRSAEncryption"},  /*  69 */
  {                0x0C,      71, 0, "sha384WithRSAEncryption"},  /*  70 */
  {                0x0D,       0, 0, "sha512WithRSAEncryption"},  /*  71 */
  {              0x07,        79, 1, "PKCS-7"                 },  /*  72 */
  {                0x01,      74, 0, "data"                   },  /*  73 */
  {                0x02,      75, 0, "signedData"             },  /*  74 */
  {                0x03,      76, 0, "envelopedData"          },  /*  75 */
  {                0x04,      77, 0, "signedAndEnvelopedData" },  /*  76 */
  {                0x05,      78, 0, "digestedData"           },  /*  77 */
  {                0x06,       0, 0, "encryptedData"          },  /*  78 */
  {              0x09,         0, 1, "PKCS-9"                 },  /*  79 */
  {                0x01,      81, 0, "E"                      },  /*  80 */
  {                0x02,      82, 0, "unstructuredName"       },  /*  81 */
  {                0x03,      83, 0, "contentType"            },  /*  82 */
  {                0x04,      84, 0, "messageDigest"          },  /*  83 */
  {                0x05,      85, 0, "signingTime"            },  /*  84 */
  {                0x06,      86, 0, "counterSignature"       },  /*  85 */
  {                0x07,      87, 0, "challengePassword"      },  /*  86 */
  {                0x08,      88, 0, "unstructuredAddress"    },  /*  87 */
  {                0x0E,       0, 0, "extensionRequest"       },  /*  88 */
  {            0x02,          92, 1, "digestAlgorithm"        },  /*  89 */
  {              0x02,        91, 0, "md2"                    },  /*  90 */
  {              0x05,         0, 0, "md5"                    },  /*  91 */
  {            0x03,           0, 1, "encryptionAlgorithm"    },  /*  92 */
  {              0x07,         0, 0, "3des-ede-cbc"           },  /*  93 */
  {0x2B,                     155, 1, ""                       },  /*  94 */
  {  0x06,                   142, 1, "dod"                    },  /*  95 */
  {    0x01,                   0, 1, "internet"               },  /*  96 */
  {      0x04,               111, 1, "private"                },  /*  97 */
  {        0x01,               0, 1, "enterprise"             },  /*  98 */
  {          0x82,           104, 1, ""                       },  /*  99 */
  {            0x37,           0, 1, "Microsoft"              },  /* 100 */
  {              0x0A,         0, 1, ""                       },  /* 101 */
  {                0x03,       0, 1, ""                       },  /* 102 */
  {                  0x03,     0, 0, "msSGC"                  },  /* 103 */
  {          0x89,             0, 1, ""                       },  /* 104 */
  {            0x31,           0, 1, ""                       },  /* 105 */
  {              0x01,         0, 1, ""                       },  /* 106 */
  {                0x01,       0, 1, ""                       },  /* 107 */
  {                  0x02,     0, 1, ""                       },  /* 108 */
  {                    0x02, 110, 0, ""                       },  /* 109 */
  {                    0x4B,   0, 0, "TCGID"                  },  /* 110 */
  {      0x05,                 0, 1, "security"               },  /* 111 */
  {        0x05,               0, 1, "mechanisms"             },  /* 112 */
  {          0x07,             0, 1, "id-pkix"                },  /* 113 */
  {            0x01,         116, 1, "id-pe"                  },  /* 114 */
  {              0x01,         0, 0, "authorityInfoAccess"    },  /* 115 */
  {            0x03,         126, 1, "id-kp"                  },  /* 116 */
  {              0x01,       118, 0, "serverAuth"             },  /* 117 */
  {              0x02,       119, 0, "clientAuth"             },  /* 118 */
  {              0x03,       120, 0, "codeSigning"            },  /* 119 */
  {              0x04,       121, 0, "emailProtection"        },  /* 120 */
  {              0x05,       122, 0, "ipsecEndSystem"         },  /* 121 */
  {              0x06,       123, 0, "ipsecTunnel"            },  /* 122 */
  {              0x07,       124, 0, "ipsecUser"              },  /* 123 */
  {              0x08,       125, 0, "timeStamping"           },  /* 124 */
  {              0x09,         0, 0, "ocspSigning"            },  /* 125 */
  {            0x08,         128, 1, "id-otherNames"          },  /* 126 */
  {              0x05,         0, 0, "xmppAddr"               },  /* 127 */
  {            0x0A,         133, 1, "id-aca"                 },  /* 128 */
  {              0x01,       130, 0, "authenticationInfo"     },  /* 129 */
  {              0x02,       131, 0, "accessIdentity"         },  /* 130 */
  {              0x03,       132, 0, "chargingIdentity"       },  /* 131 */
  {              0x04,         0, 0, "group"                  },  /* 132 */
  {            0x30,           0, 1, "id-ad"                  },  /* 133 */
  {              0x01,         0, 1, "ocsp"                   },  /* 134 */
  {                0x01,     136, 0, "basic"                  },  /* 135 */
  {                0x02,     137, 0, "nonce"                  },  /* 136 */
  {                0x03,     138, 0, "crl"                    },  /* 137 */
  {                0x04,     139, 0, "response"               },  /* 138 */
  {                0x05,     140, 0, "noCheck"                },  /* 139 */
  {                0x06,     141, 0, "archiveCutoff"          },  /* 140 */
  {                0x07,       0, 0, "serviceLocator"         },  /* 141 */
  {  0x0E,                   148, 1, "oiw"                    },  /* 142 */
  {    0x03,                   0, 1, "secsig"                 },  /* 143 */
  {      0x02,                 0, 1, "algorithms"             },  /* 144 */
  {        0x07,             146, 0, "des-cbc"                },  /* 145 */
  {        0x1A,             147, 0, "sha-1"                  },  /* 146 */
  {        0x1D,               0, 0, "sha-1WithRSASignature"  },  /* 147 */
  {  0x24,                     0, 1, "TeleTrusT"              },  /* 148 */
  {    0x03,                   0, 1, "algorithm"              },  /* 149 */
  {      0x03,                 0, 1, "signatureAlgorithm"     },  /* 150 */
  {        0x01,               0, 1, "rsaSignature"           },  /* 151 */
  {          0x02,           153, 0, "rsaSigWithripemd160"    },  /* 152 */
  {          0x03,           154, 0, "rsaSigWithripemd128"    },  /* 153 */
  {          0x04,             0, 0, "rsaSigWithripemd256"    },  /* 154 */
  {0x60,                       0, 1, ""                       },  /* 155 */
  {  0x86,                     0, 1, ""                       },  /* 156 */
  {    0x48,                   0, 1, ""                       },  /* 157 */
  {      0x01,                 0, 1, "organization"           },  /* 158 */
  {        0x65,             166, 1, "gov"                    },  /* 159 */
  {          0x03,             0, 1, "csor"                   },  /* 160 */
  {            0x04,           0, 1, "nistalgorithm"          },  /* 161 */
  {              0x02,         0, 1, "hashalgs"               },  /* 162 */
  {                0x01,     164, 0, "id-SHA-256"             },  /* 163 */
  {                0x02,     165, 0, "id-SHA-384"             },  /* 164 */
  {                0x03,       0, 0, "id-SHA-512"             },  /* 165 */
  {        0x86,               0, 1, ""                       },  /* 166 */
  {          0xf8,             0, 1, ""                       },  /* 167 */
  {            0x42,         180, 1, "netscape"               },  /* 168 */
  {              0x01,       175, 1, ""                       },  /* 169 */
  {                0x01,     171, 0, "nsCertType"             },  /* 170 */
  {                0x03,     172, 0, "nsRevocationUrl"        },  /* 171 */
  {                0x04,     173, 0, "nsCaRevocationUrl"      },  /* 172 */
  {                0x08,     174, 0, "nsCaPolicyUrl"          },  /* 173 */
  {                0x0d,       0, 0, "nsComment"              },  /* 174 */
  {              0x03,       178, 1, "directory"              },  /* 175 */
  {                0x01,       0, 1, ""                       },  /* 176 */
  {                  0x03,     0, 0, "employeeNumber"         },  /* 177 */
  {              0x04,         0, 1, "policy"                 },  /* 178 */
  {                0x01,       0, 0, "nsSGC"                  },  /* 179 */
  {            0x45,           0, 1, "verisign"               },  /* 180 */
  {              0x01,         0, 1, "pki"                    },  /* 181 */
  {                0x09,       0, 1, "attributes"             },  /* 182 */
  {                  0x02,   184, 0, "messageType"            },  /* 183 */
  {                  0x03,   185, 0, "pkiStatus"              },  /* 184 */
  {                  0x04,   186, 0, "failInfo"               },  /* 185 */
  {                  0x05,   187, 0, "senderNonce"            },  /* 186 */
  {                  0x06,   188, 0, "recipientNonce"         },  /* 187 */
  {                  0x07,   189, 0, "transID"                },  /* 188 */
  {                  0x08,     0, 0, "extensionReq"           }   /* 189 */
};
